### ISSUE TITLE
"Hide on Complete" option

### ISSUE THREAD

**Issue by hiddenman** [Zren/plasma-applet-todolist#63] opened 2021-02-22 11:18 UTC
Hi,

Thank you for the great product!

I'd like to return to the issue i posted here:
https://store.kde.org/p/1152230/

> You already have a feature to remove the completed item from the list. However, your removeItem() function deletes it from the file,but it would be much better to just do not display the completed items (when this option is enabled).
> mean that's how all other todolist-tools work: they just hide completed items, but do not delete them , because it's often very important to go back and check what was done. 

You already have this function, the only thing required is to hide completed items when the new option "Hide on Complete" is enabled.  Actually, it should be a radio-button, because it's mutually exclusive with Delete on Complete.

Thank you.

**Comment by Zren** [comment] 2021-02-22 17:09
This is a duplicate of Issue #62.

**Closed by Zren** 2021-02-22 17:09 UTC
